apiVersion: v1
kind: Service
metadata:
  name: frontend-loadbalancer
  namespace: coderev
spec:
  selector:
    app: frontend  # Совпадает с Deployment
  ports:
    - name: https
      port: 80
      targetPort: 80  # Фронтенд слушает 80 порт
      protocol: TCP
  type: LoadBalancer
