apiVersion: v1
kind: Service
metadata:
  name: frontend-loadbalancer
  namespace: coderev
spec:
  selector:
    app: frontend 
  ports:
    - name: https
      port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
